#! /bin/sh

for i in "$@"; do
	if [ -z "$i" ]; then
		continue;
	fi

	if [ ! -f "$i" ]; then
		continue;
	fi

	TYPE=`identify "$i" | grep -E -o 'JPEG|GIF|PNG'`
	OLD=`stat -c %s "$i"`

	case "$TYPE" in
		JPEG)
			jpegtran -copy none -optimize -perfect -progressive -outfile "$i.tmp" "$i"
			jpegtran -copy none -optimize -perfect -outfile "$i.tmq" "$i"
			if [ -s "$i.tmp" -a -s "$i.tmq" ]; then
				S_PROG=`stat -c %s "$i.tmp"`
				S_NORM=`stat -c %s "$i.tmq"`
				if [ $S_PROG -ge $S_NORM ]; then
					mv -f "$i.tmq" "$i"
					rm -f "$i.tmp"
				else
					mv -f "$i.tmp" "$i"
					rm -f "$i.tmq"
				fi;
			fi
		;;

		GIF)
			gifsicle -O2 -b "$i"
		;;

		PNG)
			pngcrush -q -rem alla -fix "$i" "$i.tmp"
			if [ -s "$i.tmp" ]; then
				mv -f "$i.tmp" "$i"
			else
				rm -f "$i.tmp"
			fi;
			optipng -zc6-9 -zm1-9 -zs0-3 -f0-5 -q -fix "$i"
			advpng -z -4 -q "$i"
		;;
	esac

	NEW=`stat -c %s "$i"`
	echo "$i, old size: $OLD, new size: $NEW"
done
