#! /bin/sh

for i in "$@"; do
	if [ -z "$i" ]; then
		continue;
	fi

	if [ ! -f "$i" ]; then
		continue;
	fi

	TYPE=$(identify "$i" | grep -E -o 'JPEG|GIF|PNG')
	OLD=$(stat -c %s "$i")

	case "$TYPE" in
		JPEG)
			TMP_PROG=$(mktemp imgopt.XXXXXXXXXX)
			TMP_NORM=$(mktemp imgopt.XXXXXXXXXX)
			trap "{ rm -f \"$TMP_PROG\" \"$TMP_NORM\"; exit $?; }" INT TERM EXIT

			jpegtran -copy none -optimize -perfect -progressive -outfile "$TMP_PROG" "$i"
			jpegtran -copy none -optimize -perfect -outfile "$TMP_NORM" "$i"
			if [ -s "$TMP_NORM" -a -s "$TMP_PROG" ]; then
				S_PROG=$(stat -c %s "$TMP_PROG")
				S_NORM=$(stat -c %s "$TMP_NORM")
				if [ $S_PROG -ge $S_NORM ]; then
					mv -f "$TMP_NORM" "$i"
					rm -f "$TMP_PROG"
				else
					mv -f "$TMP_PROG" "$i"
					rm -f "$TMP_NORM"
				fi
			fi

			trap - INT TERM EXIT

			# https://github.com/tjko/jpegoptim
			jpegoptim -q --strip-all "$i"
		;;

		GIF)
			gifsicle -O2 -b "$i"
		;;

		PNG)
			TMP=$(mktemp imgopt.XXXXXXXXXX)
			trap "{ rm -f \"$TMP\"; exit $?; }" INT TERM EXIT

			pngcrush -q -rem alla -fix "$i" "$TMP"
			if [ -s "$TMP" ]; then
				mv -f "$TMP" "$i"
			else
				rm -f "$TMP"
			fi

			trap - INT TERM EXIT

			optipng -zc6-9 -zm1-9 -zs0-3 -f0-5 -q -fix "$i"
			advpng -z -4 -q "$i"

			# http://advsys.net/ken/util/pngout.htm
			# http://www.jonof.id.au/pngout
			pngout "$i"
		;;
	esac

	NEW=$(stat -c %s "$i")
	echo "$i, old size: $OLD, new size: $NEW"
done
